### ISSUE TITLE
Is the default canonical map pattern correct?

### ISSUE THREAD

**Issue by dale-c-anderson** [dblenkus/ansible-postfix-aws#4]
Context: I'm adding support for Debian to the role, testing with Postfix 3.3 on Ubuntu 18.04

In [defaults](https://github.com/dblenkus/ansible-postfix-aws/blob/master/defaults/main.yml#L7), `postfix_aws_sender_canonical_maps.pattern` is `/.+` , which postfix complains about, saying that there's no regex terminator.

Changing the pattern to `/.+/` makes postfix happy, and lets the SES magic happen.

Does that pattern actually work on RedHat's postfix, or is it a typo?

**Comment by dblenkus** [comment]
I have no idea. I override this setting in all my projects, but all settings end with `/`, so you are probably right that this is a bug. 

It would be great if you can fix it in your pull request.

**Comment by dblenkus** [comment]
Fixed in https://github.com/dblenkus/ansible-postfix-aws/pull/5
